### ISSUE TITLE
Links to Note headers do not adopt header color

### ISSUE THREAD

**Issue by Kaiser-Zheng** [sergey900553/obsidian_dekurai_theme#1]
When adding a link to a note using double square brackets like `[[Notes]]`, the link text color defaults to green regardless of the header level it links to. For example:

- `### [[Notes]]` links to a level 3 header but remains green instead of blue.
- `#### [[Notes]]` links to a level 4 header but remains green instead of yellow.

Expected behavior: 

Links to note headers should adopt the color corresponding to their header level, such as:

- Links to level 3 headers should be blue

- Links to level 4 headers should be yellow

etc.

![image](https://github.com/sergey900553/obsidian_dekurai_theme/assets/65280722/4e2e5685-21c0-405e-82f1-997d36d80632)

This inconsistency between header colors and link colors for links to headers can cause confusion when scanning notes visually. I suggest making the link colors match their corresponding header colors, thanks.

**Comment by sergey900553** [comment]
The behavior is correct, since links are not divided into different types like headings with h1 h2, etc.

But even if I wanted to change it, or help you personally change it, obsidian does not provide such an opportunity, since headings and links are absolutely independent and it is impossible to write something like "link after a heading of some level".
